---

- name: source-configure | Ensure the source user exist
  user: name={{source_user}} createhome=yes

- name: source-configure | Ensure the source group exist
  group: name={{source_group}}

- name: source-configure | Ensure user ssh home exists
  file: state=directory path={{source_user_ssh_home}} owner={{source_user}} recurse=yes

- name: source-configure | Copy SSH keys
  copy: src={{item}} dest={{source_user_ssh_home}}/{{item.split('/')[-1]}} mode=0400
  with_items: source_copy_keys

- name: source-configure | Setup SSH hosts
  lineinfile: 
    line="{{item}}"
    insertafter="EOF"
    state="present"
    create="yes"
    mode="0644"
    dest="{{source_user_ssh_home}}/known_hosts"
    owner="{{source_user}}"
  with_items: source_fingerprints

- name: source-configure | Ensure source directory exists
  with_items: source_sources
  file: state=directory path={{item.dest}} owner={{source_user}} recurse=yes
