---

- name: source-hg | Ensure mercurial installed
  apt: name=mercurial
  become: yes

- name: source-hg | Ensure the repositories is synced
  hg:
    dest: "{{item.dest}}"
    force: "{{item.force|default(source_default_force)}}"
    purge: "{{item.purge|default(source_default_purge)}}"
    repo: "{{item.repo}}"
    revision: "{{item.revision|default(source_default_revision)}}"
  when: item.dest|default("") != ""
  with_items: "{{source_sources}}"
  become_user: "{{source_user}}"
  notify: source hg reload
  register: source_hg_changed
